export const productSeedData = [
  {
    name: 'Swiss Luxury Chronograph Watch',
    description: 'Exquisite Swiss-made automatic chronograph watch featuring sapphire crystal, genuine leather strap, and precise mechanical movement. Water-resistant to 100m with luminous hands and markers. A timeless piece of craftsmanship.',
    price: 3499.99,
    category: 'Watches',
    brand: 'Chronos Elite',
    stock: 15,
    images: [
      'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=800&h=800&fit=crop',
    ],
    tags: ['luxury', 'watches', 'chronograph', 'swiss-made', 'automatic', 'mens'],
    isActive: true,
  },
  {
    name: 'Designer Leather Handbag',
    description: 'Premium Italian leather handbag with signature hardware and elegant silhouette. Features multiple compartments, adjustable straps, and comes with dust bag. Perfect for everyday luxury or special occasions.',
    price: 2899.00,
    category: 'Fashion',
    brand: 'Maison Laurent',
    stock: 22,
    images: [
      'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1591561954557-26941169b49e?w=800&h=800&fit=crop',
    ],
    tags: ['luxury', 'fashion', 'handbag', 'leather', 'designer', 'womens'],
    isActive: true,
  },
  {
    name: 'Premium Wireless Noise-Cancelling Earbuds',
    description: 'State-of-the-art wireless earbuds with advanced noise cancellation technology, premium sound quality, and 30-hour battery life. Includes luxury charging case with wireless charging capability.',
    price: 449.99,
    category: 'Electronics',
    brand: 'AudioLux',
    stock: 45,
    images: [
      'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1606841837239-c5a1a4a07af7?w=800&h=800&fit=crop',
    ],
    tags: ['electronics', 'audio', 'wireless', 'premium', 'noise-cancelling'],
    isActive: true,
  },
  {
    name: 'Luxury Anti-Aging Skincare Collection',
    description: 'Complete luxury skincare set featuring advanced anti-aging serum, rich moisturizer, and gentle cleanser. Formulated with rare botanicals and cutting-edge peptides. Dermatologist-tested and cruelty-free.',
    price: 685.00,
    category: 'Beauty',
    brand: 'Belle Radiance',
    stock: 35,
    images: [
      'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800&h=800&fit=crop',
    ],
    tags: ['luxury', 'skincare', 'beauty', 'anti-aging', 'premium'],
    isActive: true,
  },
  {
    name: 'Designer Aviator Sunglasses',
    description: 'Iconic aviator sunglasses with polarized lenses and lightweight titanium frame. UV400 protection with anti-reflective coating. Includes premium case and cleaning cloth.',
    price: 425.00,
    category: 'Accessories',
    brand: 'Visionaire',
    stock: 40,
    images: [
      'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=800&h=800&fit=crop',
    ],
    tags: ['luxury', 'sunglasses', 'designer', 'accessories', 'eyewear'],
    isActive: true,
  },
  {
    name: 'Premium Leather Bifold Wallet',
    description: 'Handcrafted from finest full-grain leather with elegant stitching and RFID protection. Features multiple card slots, bill compartment, and ID window. Ages beautifully with use.',
    price: 295.00,
    category: 'Accessories',
    brand: 'Artisan Leather Co.',
    stock: 50,
    images: [
      'https://images.unsplash.com/photo-1627123424574-724758594e93?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1608571607007-c36db7f2b3d8?w=800&h=800&fit=crop',
    ],
    tags: ['luxury', 'leather', 'wallet', 'accessories', 'mens', 'rfid'],
    isActive: true,
  },
  {
    name: 'Haute Couture Eau de Parfum',
    description: 'Exclusive fragrance with top notes of bergamot and jasmine, heart notes of rose and amber, and base notes of sandalwood and vanilla. 100ml bottle with elegant atomizer. Long-lasting luxury scent.',
    price: 285.00,
    category: 'Beauty',
    brand: 'Parfumerie Élégance',
    stock: 60,
    images: [
      'https://images.unsplash.com/photo-1541643600914-78b084683601?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1528821128474-27f963b062bf?w=800&h=800&fit=crop',
    ],
    tags: ['luxury', 'perfume', 'fragrance', 'beauty', 'eau-de-parfum'],
    isActive: true,
  },
  {
    name: 'Cashmere Blend Luxury Scarf',
    description: 'Ultra-soft cashmere and silk blend scarf with signature pattern. Lightweight yet warm, perfect for any season. Hand-finished edges and comes in elegant gift box.',
    price: 395.00,
    category: 'Fashion',
    brand: 'Casa Dolce',
    stock: 30,
    images: [
      'https://images.unsplash.com/photo-1520903920243-00d872a2d1c9?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=800&h=800&fit=crop',
    ],
    tags: ['luxury', 'fashion', 'scarf', 'cashmere', 'accessories'],
    isActive: true,
  },
  {
    name: 'Elegant Diamond-Accented Watch',
    description: 'Sophisticated womens watch with mother-of-pearl dial, genuine diamond hour markers, and stainless steel bracelet. Swiss quartz movement with scratch-resistant sapphire crystal.',
    price: 1895.00,
    category: 'Watches',
    brand: 'Celestial Time',
    stock: 18,
    images: [
      'https://images.unsplash.com/photo-1594534475808-b18fc33b045e?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1509048191080-d2984bad6ae5?w=800&h=800&fit=crop',
    ],
    tags: ['luxury', 'watches', 'diamonds', 'womens', 'elegant'],
    isActive: true,
  },
  {
    name: 'Deluxe Spa & Wellness Gift Set',
    description: 'Indulgent spa collection featuring aromatherapy oils, luxury bath salts, silk eye mask, and premium body lotion. Presented in a beautiful keepsake box. Perfect for self-care or gifting.',
    price: 245.00,
    category: 'Beauty',
    brand: 'Serenity Luxe',
    stock: 55,
    images: [
      'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1600334089648-b0d9d3028eb2?w=800&h=800&fit=crop',
    ],
    tags: ['luxury', 'spa', 'wellness', 'gift', 'beauty', 'self-care'],
    isActive: true,
  },
  {
    name: 'Professional Espresso Machine',
    description: 'Premium semi-automatic espresso machine with dual boiler system, PID temperature control, and commercial-grade steam wand. Crafted from stainless steel with elegant design.',
    price: 2199.00,
    category: 'Home',
    brand: 'Barista Pro',
    stock: 12,
    images: [
      'https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=800&h=800&fit=crop',
    ],
    tags: ['luxury', 'home', 'coffee', 'espresso', 'appliance', 'premium'],
    isActive: true,
  },
  {
    name: 'Designer Silk Tie Collection',
    description: 'Set of three handcrafted silk ties with sophisticated patterns. Made from 100% pure mulberry silk with precise hand-stitching. Includes luxury presentation box.',
    price: 385.00,
    category: 'Fashion',
    brand: 'Gentleman\'s Choice',
    stock: 28,
    images: [
      'https://images.unsplash.com/photo-1585435557343-3b092031a831?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1618886614638-80e3c103d31a?w=800&h=800&fit=crop',
    ],
    tags: ['luxury', 'fashion', 'ties', 'silk', 'mens', 'formal'],
    isActive: true,
  },
];
