export const productSeedData = [
  {
    name: 'Swiss Luxury Chronograph Watch',
    description: 'Exquisite Swiss-made automatic chronograph watch featuring sapphire crystal, genuine leather strap, and precise mechanical movement. Water-resistant to 100m with luminous hands and markers. A timeless piece of craftsmanship.',
    price: 3200,
    category: 'Watches',
    brand: 'Chronos Elite',
    stock: 15,
    images: [
      'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=800&h=800&fit=crop',
    ],
    tags: ['luxury', 'watches', 'chronograph', 'swiss-made', 'automatic', 'mens'],
    isActive: true,
  },
  {
    name: 'Designer Leather Handbag',
    description: 'Premium Italian leather handbag with signature hardware and elegant silhouette. Features multiple compartments, adjustable straps, and comes with dust bag. Perfect for everyday luxury or special occasions.',
    price: 2400,
    category: 'Fashion',
    brand: 'Maison Laurent',
    stock: 22,
    images: [
      'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1591561954557-26941169b49e?w=800&h=800&fit=crop',
    ],
    tags: ['luxury', 'fashion', 'handbag', 'leather', 'designer', 'womens'],
    isActive: true,
  },
  {
    name: 'Premium Wireless Noise-Cancelling Earbuds',
    description: 'State-of-the-art wireless earbuds with advanced noise cancellation technology, premium sound quality, and 30-hour battery life. Includes luxury charging case with wireless charging capability.',
    price: 3700,
    category: 'Electronics',
    brand: 'AudioLux',
    stock: 45,
    images: [
      'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1606841837239-c5a1a4a07af7?w=800&h=800&fit=crop',
    ],
    tags: ['electronics', 'audio', 'wireless', 'premium', 'noise-cancelling'],
    isActive: true,
  },
  {
    name: 'Luxury Anti-Aging Skincare Collection',
    description: 'Complete luxury skincare set featuring advanced anti-aging serum, rich moisturizer, and gentle cleanser. Formulated with rare botanicals and cutting-edge peptides. Dermatologist-tested and cruelty-free.',
    price: 5680,
    category: 'Beauty',
    brand: 'Belle Radiance',
    stock: 35,
    images: [
      'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800&h=800&fit=crop',
    ],
    tags: ['luxury', 'skincare', 'beauty', 'anti-aging', 'premium'],
    isActive: true,
  },
  {
    name: 'Designer Aviator Sunglasses',
    description: 'Iconic aviator sunglasses with polarized lenses and lightweight titanium frame. UV400 protection with anti-reflective coating. Includes premium case and cleaning cloth.',
    price: 3520,
    category: 'Accessories',
    brand: 'Visionaire',
    stock: 40,
    images: [
      'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=800&h=800&fit=crop',
    ],
    tags: ['luxury', 'sunglasses', 'designer', 'accessories', 'eyewear'],
    isActive: true,
  },
  {
    name: 'Premium Leather Bifold Wallet',
    description: 'Handcrafted from finest full-grain leather with elegant stitching and RFID protection. Features multiple card slots, bill compartment, and ID window. Ages beautifully with use.',
    price: 2445,
    category: 'Accessories',
    brand: 'Artisan Leather Co.',
    stock: 50,
    images: [
      'https://images.unsplash.com/photo-1627123424574-724758594e93?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1608571607007-c36db7f2b3d8?w=800&h=800&fit=crop',
    ],
    tags: ['luxury', 'leather', 'wallet', 'accessories', 'mens', 'rfid'],
    isActive: true,
  },
  {
    name: 'Haute Couture Eau de Parfum',
    description: 'Exclusive fragrance with top notes of bergamot and jasmine, heart notes of rose and amber, and base notes of sandalwood and vanilla. 100ml bottle with elegant atomizer. Long-lasting luxury scent.',
    price: 2365,
    category: 'Beauty',
    brand: 'Parfumerie Élégance',
    stock: 60,
    images: [
      'https://images.unsplash.com/photo-1541643600914-78b084683601?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1528821128474-27f963b062bf?w=800&h=800&fit=crop',
    ],
    tags: ['luxury', 'perfume', 'fragrance', 'beauty', 'eau-de-parfum'],
    isActive: true,
  },
  {
    name: 'Cashmere Blend Luxury Scarf',
    description: 'Ultra-soft cashmere and silk blend scarf with signature pattern. Lightweight yet warm, perfect for any season. Hand-finished edges and comes in elegant gift box.',
    price: 3270,
    category: 'Fashion',
    brand: 'Casa Dolce',
    stock: 30,
    images: [
      'https://images.unsplash.com/photo-1520903920243-00d872a2d1c9?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=800&h=800&fit=crop',
    ],
    tags: ['luxury', 'fashion', 'scarf', 'cashmere', 'accessories'],
    isActive: true,
  },
  {
    name: 'Elegant Diamond-Accented Watch',
    description: 'Sophisticated womens watch with mother-of-pearl dial, genuine diamond hour markers, and stainless steel bracelet. Swiss quartz movement with scratch-resistant sapphire crystal.',
    price: 15750,
    category: 'Watches',
    brand: 'Celestial Time',
    stock: 18,
    images: [
      'https://images.unsplash.com/photo-1594534475808-b18fc33b045e?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1509048191080-d2984bad6ae5?w=800&h=800&fit=crop',
    ],
    tags: ['luxury', 'watches', 'diamonds', 'womens', 'elegant'],
    isActive: true,
  },
  {
    name: 'Deluxe Spa & Wellness Gift Set',
    description: 'Indulgent spa collection featuring aromatherapy oils, luxury bath salts, silk eye mask, and premium body lotion. Presented in a beautiful keepsake box. Perfect for self-care or gifting.',
    price: 2035,
    category: 'Beauty',
    brand: 'Serenity Luxe',
    stock: 55,
    images: [
      'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1600334089648-b0d9d3028eb2?w=800&h=800&fit=crop',
    ],
    tags: ['luxury', 'spa', 'wellness', 'gift', 'beauty', 'self-care'],
    isActive: true,
  },
  {
    name: 'Professional Espresso Machine',
    description: 'Premium semi-automatic espresso machine with dual boiler system, PID temperature control, and commercial-grade steam wand. Crafted from stainless steel with elegant design.',
    price: 18250,
    category: 'Home',
    brand: 'Barista Pro',
    stock: 12,
    images: [
      'https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=800&h=800&fit=crop',
    ],
    tags: ['luxury', 'home', 'coffee', 'espresso', 'appliance', 'premium'],
    isActive: true,
  },
  {
    name: 'Designer Silk Tie Collection',
    description: 'Set of three handcrafted silk ties with sophisticated patterns. Made from 100% pure mulberry silk with precise hand-stitching. Includes luxury presentation box.',
    price: 3150,
    category: 'Fashion',
    brand: 'Gentleman\'s Choice',
    stock: 28,
    images: [
      'https://images.unsplash.com/photo-1585435557343-3b092031a831?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1618886614638-80e3c103d31a?w=800&h=800&fit=crop',
    ],
    tags: ['luxury', 'fashion', 'ties', 'silk', 'mens', 'formal'],
    isActive: true,
  },
  {
    name: 'Silk Blouse',
    description: 'Premium silk top',
    price: 5999,
    category: 'Fashion',
    brand: 'Silk Threads',
    stock: 20,
    images: [
      'https://images.unsplash.com/photo-1551028719-00167b16ebc5?w=500&h=400&fit=crop',
    ],
    tags: ['fashion', 'silk', 'blouse', 'premium', 'womens'],
    isActive: true,
  },
  {
    name: 'Diamond Ring',
    description: 'Luxury engagement ring',
    price: 14999,
    category: 'Jewelry',
    brand: 'Eternal Gems',
    stock: 5,
    images: [
      'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=500&h=400&fit=crop',
    ],
    tags: ['jewelry', 'diamond', 'ring', 'luxury', 'engagement'],
    isActive: true,
  },
  {
    name: 'Wool Coat',
    description: 'Premium winter coat',
    price: 11299,
    category: 'Fashion',
    brand: 'Winter Warmth',
    stock: 12,
    images: [
      'https://images.unsplash.com/photo-1539533057592-4d2c3be5f226?w=500&h=400&fit=crop',
    ],
    tags: ['fashion', 'coat', 'wool', 'winter', 'premium'],
    isActive: true,
  },
  {
    name: 'Leather Belt',
    description: 'Luxury leather accessory',
    price: 3349,
    category: 'Accessories',
    brand: 'Belt Masters',
    stock: 25,
    images: [
      'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=500&h=400&fit=crop',
    ],
    tags: ['accessories', 'leather', 'belt', 'luxury', 'mens'],
    isActive: true,
  },
  {
    name: 'Gold Bracelet',
    description: 'Premium bracelet',
    price: 7499,
    category: 'Jewelry',
    brand: 'Golden Touch',
    stock: 15,
    images: [
      'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=500&h=400&fit=crop',
    ],
    tags: ['jewelry', 'gold', 'bracelet', 'premium', 'luxury'],
    isActive: true,
  },
  {
    name: 'Luxury Mirror',
    description: 'Decorative mirror',
    price: 7099,
    category: 'Home',
    brand: 'Reflections',
    stock: 8,
    images: [
      'https://images.unsplash.com/photo-1578500494198-246f612d03b3?w=500&h=400&fit=crop',
    ],
    tags: ['home', 'mirror', 'decorative', 'luxury', 'decor'],
    isActive: true,
  },
  {
    name: 'Designer Wallet',
    description: 'Premium leather wallet',
    price: 5599,
    category: 'Accessories',
    brand: 'Wallet World',
    stock: 30,
    images: [
      'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=500&h=400&fit=crop',
    ],
    tags: ['accessories', 'wallet', 'leather', 'designer', 'premium'],
    isActive: true,
  },
  {
    name: 'Luxury Candle',
    description: 'Premium scented candle',
    price: 2999,
    category: 'Home',
    brand: 'Aromatic Bliss',
    stock: 50,
    images: [
      'https://images.unsplash.com/photo-1590080876-55cd97bcaec0?w=500&h=400&fit=crop',
    ],
    tags: ['home', 'candle', 'scented', 'luxury', 'aromatic'],
    isActive: true,
  },
  {
    name: 'Premium Shoes',
    description: 'High-end leather shoes',
    price: 9349,
    category: 'Fashion',
    brand: 'Step Elite',
    stock: 14,
    images: [
      'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=500&h=400&fit=crop',
    ],
    tags: ['fashion', 'shoes', 'leather', 'premium', 'mens'],
    isActive: true,
  },
  {
    name: 'Silk Pillowcase',
    description: 'Luxury silk bedding',
    price: 2599,
    category: 'Home',
    brand: 'Silk Dreams',
    stock: 35,
    images: [
      'https://images.unsplash.com/photo-1631049307038-da0ec89d4b0c?w=500&h=400&fit=crop',
    ],
    tags: ['home', 'bedding', 'silk', 'pillowcase', 'luxury'],
    isActive: true,
  },
  {
    name: 'Designer Hat',
    description: 'Premium fashion hat',
    price: 4849,
    category: 'Accessories',
    brand: 'Hat House',
    stock: 18,
    images: [
      'https://images.unsplash.com/photo-1529260503372-4798221bb6d5?w=500&h=400&fit=crop',
    ],
    tags: ['accessories', 'hat', 'fashion', 'designer', 'premium'],
    isActive: true,
  },
  {
    name: 'Luxury Bedding',
    description: 'Premium Egyptian cotton sheets',
    price: 10099,
    category: 'Home',
    brand: 'Sleep Luxury',
    stock: 20,
    images: [
      'https://images.unsplash.com/photo-1540932239986-310128078ceb?w=500&h=400&fit=crop',
    ],
    tags: ['home', 'bedding', 'cotton', 'luxury', 'sheets'],
    isActive: true,
  },
  {
    name: 'Gold Earrings',
    description: 'Luxury drop earrings',
    price: 6349,
    category: 'Jewelry',
    brand: 'Jewel Crown',
    stock: 22,
    images: [
      'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=500&h=400&fit=crop',
    ],
    tags: ['jewelry', 'earrings', 'gold', 'luxury', 'womens'],
    isActive: true,
  },
  {
    name: 'Designer Gloves',
    description: 'Premium leather gloves',
    price: 3699,
    category: 'Accessories',
    brand: 'Glove Masters',
    stock: 28,
    images: [
      'https://images.unsplash.com/photo-1582033213332-6bde1d1b3c63?w=500&h=400&fit=crop',
    ],
    tags: ['accessories', 'gloves', 'leather', 'designer', 'premium'],
    isActive: true,
  },
  {
    name: 'Luxury Throw',
    description: 'Premium cashmere throw blanket',
    price: 8249,
    category: 'Home',
    brand: 'Cozy Comfort',
    stock: 12,
    images: [
      'https://images.unsplash.com/photo-1578500494198-246f612d03b3?w=500&h=400&fit=crop',
    ],
    tags: ['home', 'throw', 'cashmere', 'blanket', 'luxury'],
    isActive: true,
  },
];
