export const productSeedData = [
  {
    name: 'Swiss Luxury Chronograph Watch',
    description: 'Exquisite Swiss-made automatic chronograph watch featuring sapphire crystal, genuine leather strap, and precise mechanical movement. Water-resistant to 100m with luminous hands and markers. A timeless piece of craftsmanship.',
    price: 3499.99,
    category: 'Watches',
    brand: 'Chronos Elite',
    stock: 15,
    images: [
      'https://placehold.co/800x800/1a1a1a/ffffff?text=Luxury+Watch',
      'https://placehold.co/800x800/2a2a2a/ffffff?text=Watch+Detail',
    ],
    tags: ['luxury', 'watches', 'chronograph', 'swiss-made', 'automatic', 'mens'],
    isActive: true,
  },
  {
    name: 'Designer Leather Handbag',
    description: 'Premium Italian leather handbag with signature hardware and elegant silhouette. Features multiple compartments, adjustable straps, and comes with dust bag. Perfect for everyday luxury or special occasions.',
    price: 2899.00,
    category: 'Fashion',
    brand: 'Maison Laurent',
    stock: 22,
    images: [
      'https://placehold.co/800x800/8b4513/ffffff?text=Designer+Handbag',
      'https://placehold.co/800x800/a0522d/ffffff?text=Bag+Interior',
    ],
    tags: ['luxury', 'fashion', 'handbag', 'leather', 'designer', 'womens'],
    isActive: true,
  },
  {
    name: 'Premium Wireless Noise-Cancelling Earbuds',
    description: 'State-of-the-art wireless earbuds with advanced noise cancellation technology, premium sound quality, and 30-hour battery life. Includes luxury charging case with wireless charging capability.',
    price: 449.99,
    category: 'Electronics',
    brand: 'AudioLux',
    stock: 45,
    images: [
      'https://placehold.co/800x800/000000/ffffff?text=Premium+Earbuds',
      'https://placehold.co/800x800/1a1a1a/ffffff?text=Charging+Case',
    ],
    tags: ['electronics', 'audio', 'wireless', 'premium', 'noise-cancelling'],
    isActive: true,
  },
  {
    name: 'Luxury Anti-Aging Skincare Collection',
    description: 'Complete luxury skincare set featuring advanced anti-aging serum, rich moisturizer, and gentle cleanser. Formulated with rare botanicals and cutting-edge peptides. Dermatologist-tested and cruelty-free.',
    price: 685.00,
    category: 'Beauty',
    brand: 'Belle Radiance',
    stock: 35,
    images: [
      'https://placehold.co/800x800/f5f5dc/000000?text=Skincare+Set',
      'https://placehold.co/800x800/fffaf0/000000?text=Product+Details',
    ],
    tags: ['luxury', 'skincare', 'beauty', 'anti-aging', 'premium'],
    isActive: true,
  },
  {
    name: 'Designer Aviator Sunglasses',
    description: 'Iconic aviator sunglasses with polarized lenses and lightweight titanium frame. UV400 protection with anti-reflective coating. Includes premium case and cleaning cloth.',
    price: 425.00,
    category: 'Accessories',
    brand: 'Visionaire',
    stock: 40,
    images: [
      'https://placehold.co/800x800/2f4f4f/ffffff?text=Designer+Sunglasses',
      'https://placehold.co/800x800/708090/ffffff?text=Side+View',
    ],
    tags: ['luxury', 'sunglasses', 'designer', 'accessories', 'eyewear'],
    isActive: true,
  },
  {
    name: 'Premium Leather Bifold Wallet',
    description: 'Handcrafted from finest full-grain leather with elegant stitching and RFID protection. Features multiple card slots, bill compartment, and ID window. Ages beautifully with use.',
    price: 295.00,
    category: 'Accessories',
    brand: 'Artisan Leather Co.',
    stock: 50,
    images: [
      'https://placehold.co/800x800/654321/ffffff?text=Leather+Wallet',
      'https://placehold.co/800x800/8b4513/ffffff?text=Wallet+Open',
    ],
    tags: ['luxury', 'leather', 'wallet', 'accessories', 'mens', 'rfid'],
    isActive: true,
  },
  {
    name: 'Haute Couture Eau de Parfum',
    description: 'Exclusive fragrance with top notes of bergamot and jasmine, heart notes of rose and amber, and base notes of sandalwood and vanilla. 100ml bottle with elegant atomizer. Long-lasting luxury scent.',
    price: 285.00,
    category: 'Beauty',
    brand: 'Parfumerie Élégance',
    stock: 60,
    images: [
      'https://placehold.co/800x800/dda0dd/000000?text=Luxury+Perfume',
      'https://placehold.co/800x800/e6e6fa/000000?text=Bottle+Detail',
    ],
    tags: ['luxury', 'perfume', 'fragrance', 'beauty', 'eau-de-parfum'],
    isActive: true,
  },
  {
    name: 'Cashmere Blend Luxury Scarf',
    description: 'Ultra-soft cashmere and silk blend scarf with signature pattern. Lightweight yet warm, perfect for any season. Hand-finished edges and comes in elegant gift box.',
    price: 395.00,
    category: 'Fashion',
    brand: 'Casa Dolce',
    stock: 30,
    images: [
      'https://placehold.co/800x800/4682b4/ffffff?text=Cashmere+Scarf',
      'https://placehold.co/800x800/5f9ea0/ffffff?text=Scarf+Pattern',
    ],
    tags: ['luxury', 'fashion', 'scarf', 'cashmere', 'accessories'],
    isActive: true,
  },
  {
    name: 'Elegant Diamond-Accented Watch',
    description: 'Sophisticated womens watch with mother-of-pearl dial, genuine diamond hour markers, and stainless steel bracelet. Swiss quartz movement with scratch-resistant sapphire crystal.',
    price: 1895.00,
    category: 'Watches',
    brand: 'Celestial Time',
    stock: 18,
    images: [
      'https://placehold.co/800x800/c0c0c0/000000?text=Diamond+Watch',
      'https://placehold.co/800x800/d3d3d3/000000?text=Watch+Close-up',
    ],
    tags: ['luxury', 'watches', 'diamonds', 'womens', 'elegant'],
    isActive: true,
  },
  {
    name: 'Deluxe Spa & Wellness Gift Set',
    description: 'Indulgent spa collection featuring aromatherapy oils, luxury bath salts, silk eye mask, and premium body lotion. Presented in a beautiful keepsake box. Perfect for self-care or gifting.',
    price: 245.00,
    category: 'Beauty',
    brand: 'Serenity Luxe',
    stock: 55,
    images: [
      'https://placehold.co/800x800/f0e68c/000000?text=Spa+Gift+Set',
      'https://placehold.co/800x800/fafad2/000000?text=Set+Contents',
    ],
    tags: ['luxury', 'spa', 'wellness', 'gift', 'beauty', 'self-care'],
    isActive: true,
  },
  {
    name: 'Professional Espresso Machine',
    description: 'Premium semi-automatic espresso machine with dual boiler system, PID temperature control, and commercial-grade steam wand. Crafted from stainless steel with elegant design.',
    price: 2199.00,
    category: 'Home',
    brand: 'Barista Pro',
    stock: 12,
    images: [
      'https://placehold.co/800x800/696969/ffffff?text=Espresso+Machine',
      'https://placehold.co/800x800/778899/ffffff?text=Machine+Detail',
    ],
    tags: ['luxury', 'home', 'coffee', 'espresso', 'appliance', 'premium'],
    isActive: true,
  },
  {
    name: 'Designer Silk Tie Collection',
    description: 'Set of three handcrafted silk ties with sophisticated patterns. Made from 100% pure mulberry silk with precise hand-stitching. Includes luxury presentation box.',
    price: 385.00,
    category: 'Fashion',
    brand: 'Gentleman\'s Choice',
    stock: 28,
    images: [
      'https://placehold.co/800x800/191970/ffffff?text=Silk+Ties',
      'https://placehold.co/800x800/4169e1/ffffff?text=Tie+Pattern',
    ],
    tags: ['luxury', 'fashion', 'ties', 'silk', 'mens', 'formal'],
    isActive: true,
  },
];
